version: 2.1

jobs:
  build-for-linux:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: make -C src

workflows:
  version: 2.1
  build:
    jobs:
      - build-for-linux
