name: Cygwin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-cygwin@v3
      with:
        packages: make gcc-g++
    - name: make
      run: make -j
    - name: version
      run: ./rvlq --version
    - name: test
      run: ./rvlq test/Tags.txt test/Source.txt
