name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j
    - name: version
      run: ./rvlq --version
    - name: help
      run: ./rvlq --help
    - name: test
      run: ./rvlq test/Tags.txt test/Source.txt
