name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: WhereAmI
      run: Get-Location
    - name: Create release
      run: |
        cmd /c "md rvlq-windows_v0"
        cmd /c "copy src/* rvlq-windows_v0/"
        cmd /c "7z a rvlq-windows_v0.zip rvlq-windows_v0"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rvlq-windows_v0.zip
#        asset_name: rvlq_windows$tag.xcfg
        tag: 20010101
        overwrite: true
        body: "This is my release text"