name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j
    - name: version
      if: {{ true }}
      run: ./rvlq --version
    - name: help
      if: {{ true }}
      run: ./rvlq --help
    - name: test
      if: {{ true }}
      run: ./rvlq test/Tags.txt test/Source.txt
