name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: WhereAmI
      run: Get-Location
    - name: build
      run: MSBuild rvlq.vcxproj
    - name: version
      run: Start-Process -NoNewWindow -FilePath ".\rvlq.exe" -ArgumentList "--version"
    - name: test
      run: Start-Process -NoNewWindow -FilePath ".\rvlq.exe" -ArgumentList "test\Tags.txt test\Source.txt"