name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: WhereAmI
      run: Get-Location
    - name: build
      run: MSBuild rvlq.vcxproj
    - name: version
      run: D:\a\rvlq-cli\rvlq-cli\rvlq.exe --version
    - name: version2
      run: "& rvlq.exe --version"
    - name: version3
      run: Start-Process -NoNewWindow -FilePath ".\rvlq.exe" -ArgumentList "--version"